[package]
name = "forzanalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.3.10"
image = "0.23.14"
egui_sdl2_gl = { git = "https://github.com/ArjunNair/egui_sdl2_gl.git" }
