name: Release binaries for all platforms

on:
  push:
    tags:
      - "v*"

jobs:
  artifacts:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libgtk-3-dev libxcb-present-dev
        if: ${{ matrix.os == 'ubuntu' }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: TheDoctor0/zip-release@0.6.0
        with:
          directory: target
          path: "release/forzanalyst release/forzanalyst.exe"
          filename: forzanalyst-${{ matrix.os }}-${{ github.ref_name }}.zip
      - uses: actions/upload-artifact@v2
        with:
          name: forzanalyst-${{ matrix.os }}-${{ github.ref_name }}.zip
          path: target/forzanalyst-${{ matrix.os }}-${{ github.ref_name }}.zip

  release:
    runs-on: ubuntu-latest
    needs: artifacts
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ForzAnalyst ${{ github.ref_name }}
          draft: false
          prerelease: false

  add:
    runs-on: ubuntu-latest
    needs: [artifacts, release]
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: forzanalyst-${{ matrix.os }}-${{ github.ref_name }}.zip
      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./forzanalyst-${{ matrix.os }}-${{ github.ref_name }}.zip
          asset_name: forzanalyst-${{ matrix.os }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip
